import type { FailureType } from "./schemas";
import { taxonomyEntrySchema } from "./schemas";

export const failureTaxonomy = [
  {
    id: "MISSING_ENV_VAR",
    label: "Missing environment variable",
    description: "The build or runtime expects an environment variable that is unset in Vercel.",
    symptoms: ["process.env access throws", "Missing required environment variable", "env validation failure"],
    likelyCauses: ["Variable exists locally but not in Vercel", "Preview/production scopes differ", "Public variable prefix is missing"],
    fixSteps: ["Add the missing variable in Vercel Project Settings", "Confirm preview and production scopes", "Rebuild after the variable is saved"],
    verificationCommands: ["npm run build", "vercel env ls", "vercel --prod"],
    preventionChecks: ["Keep .env.example complete", "Validate env at boot with safe error messages", "Document variable scope"],
  },
  {
    id: "TYPESCRIPT_ERROR",
    label: "TypeScript compile error",
    description: "The Next.js build failed during type checking or transpilation.",
    symptoms: ["Type error:", "Property does not exist", "Type is not assignable"],
    likelyCauses: ["Stale interface", "Incorrect component props", "Unchecked API response shape"],
    fixSteps: ["Open the referenced file and align the type contract", "Add a narrow guard or schema parse", "Run typecheck before redeploying"],
    verificationCommands: ["npm run typecheck", "npm run build"],
    preventionChecks: ["Keep strict TypeScript enabled", "Test representative component props", "Validate external data with schemas"],
  },
  {
    id: "MODULE_NOT_FOUND",
    label: "Module not found",
    description: "The bundler cannot resolve an import or package.",
    symptoms: ["Module not found", "Can't resolve", "Cannot find module"],
    likelyCauses: ["Dependency missing from package.json", "Incorrect import casing", "Path alias mismatch"],
    fixSteps: ["Install or add the dependency", "Fix import path casing", "Verify tsconfig path aliases"],
    verificationCommands: ["npm install", "npm run build"],
    preventionChecks: ["Run clean installs in CI", "Avoid case-only path differences", "Keep lockfile committed"],
  },
  {
    id: "NEXT_BUILD_ERROR",
    label: "Next.js build or route error",
    description: "Next.js detected an invalid route, server/client boundary issue, or dynamic rendering violation.",
    symptoms: ["Dynamic server usage", "Failed to collect page data", "useSearchParams should be wrapped"],
    likelyCauses: ["Dynamic API used in static route", "Server-only code imported into client component", "Route handler throws during build"],
    fixSteps: ["Move dynamic work behind a route handler or server boundary", "Mark the route dynamic when appropriate", "Guard build-time data access"],
    verificationCommands: ["npm run build"],
    preventionChecks: ["Smoke test production builds locally", "Keep server/client boundaries explicit", "Avoid build-time secret reads in pages"],
  },
  {
    id: "NEXT_STATIC_GENERATION_ERROR",
    label: "Next.js static generation failure",
    description: "Static prerendering failed because a page used dynamic data or threw during generation.",
    symptoms: ["Error occurred prerendering page", "Export encountered errors", "Generating static pages failed"],
    likelyCauses: ["Dynamic data used during static generation", "Build-time fetch failed", "Page code threw during prerender"],
    fixSteps: ["Move dynamic access behind a route handler", "Add explicit dynamic rendering when appropriate", "Guard build-time fetches with safe fallbacks"],
    verificationCommands: ["npm run build"],
    preventionChecks: ["Run production builds locally", "Avoid unguarded build-time fetches", "Document static versus dynamic route intent"],
  },
  {
    id: "APP_ROUTER_ROUTE_HANDLER_ERROR",
    label: "Next.js App Router route handler error",
    description: "An App Router route handler failed because of request handling, runtime, or response-shape issues.",
    symptoms: ["Route handler failed", "app/api", "Failed to collect page data for /api"],
    likelyCauses: ["Route handler throws at build/runtime", "Invalid Request/Response usage", "Server-only dependency imported incorrectly"],
    fixSteps: ["Validate route input with a schema", "Return user-safe errors", "Declare runtime only when required"],
    verificationCommands: ["npm run typecheck", "npm run build"],
    preventionChecks: ["Unit test route handlers", "Keep provider code server-only", "Avoid reading required secrets during build"],
  },
  {
    id: "PACKAGE_INSTALL_ERROR",
    label: "Package install error",
    description: "Install failed before the app could build.",
    symptoms: ["ERESOLVE", "npm ERR!", "peer dependency", "lockfile"],
    likelyCauses: ["Peer dependency conflict", "Stale lockfile", "Unsupported Node/npm version"],
    fixSteps: ["Resolve the peer dependency range", "Regenerate the lockfile with the project package manager", "Pin Node version if needed"],
    verificationCommands: ["npm install", "npm run build"],
    preventionChecks: ["Commit lockfiles", "Document Node version", "Avoid mixing package managers"],
  },
  {
    id: "PNPM_LOCKFILE_MISMATCH",
    label: "pnpm lockfile mismatch",
    description: "Install failed because pnpm lockfile state does not match package.json.",
    symptoms: ["ERR_PNPM_OUTDATED_LOCKFILE", "Cannot install with frozen-lockfile", "pnpm-lock.yaml"],
    likelyCauses: ["package.json changed without lockfile update", "CI uses frozen lockfile", "Package manager mismatch"],
    fixSteps: ["Regenerate pnpm-lock.yaml with pnpm install", "Commit package.json and lockfile together", "Confirm Vercel uses the intended package manager"],
    verificationCommands: ["pnpm install --frozen-lockfile", "pnpm build"],
    preventionChecks: ["Avoid mixing npm and pnpm", "Run clean installs in CI", "Commit lockfile updates with dependency changes"],
  },
  {
    id: "PACKAGE_JSON_PARSE",
    label: "Package JSON parse error",
    description: "The build cannot parse package.json or another package-manager manifest.",
    symptoms: ["Failed to parse package.json", "Unexpected token in JSON", "JSON.parse", "EJSONPARSE"],
    likelyCauses: ["Invalid JSON syntax", "Trailing comma", "Merge conflict marker left in package.json"],
    fixSteps: ["Open package.json and remove invalid JSON syntax", "Validate the manifest with npm before reinstalling", "Regenerate the lockfile only after the manifest parses cleanly"],
    verificationCommands: ["node -e \"JSON.parse(require('fs').readFileSync('package.json','utf8'))\"", "npm install", "npm run build"],
    preventionChecks: ["Keep package.json edits reviewed", "Run JSON validation in CI", "Avoid hand-editing lockfiles"],
  },
  {
    id: "SPAWN_PERMISSION",
    label: "Spawn or permission failure",
    description: "The build cannot execute a script, binary, or package-manager command because of permissions or missing executable access.",
    symptoms: ["EACCES", "EPERM", "spawn", "permission denied", "not executable"],
    likelyCauses: ["Script file lacks execute permission", "Postinstall binary is unavailable", "Build script assumes a local shell capability unavailable in Vercel"],
    fixSteps: ["Check the failing script or binary path", "Replace shell-specific assumptions with portable npm scripts", "Ensure generated or vendored binaries are available during install"],
    verificationCommands: ["npm install", "npm run build"],
    preventionChecks: ["Keep scripts portable across Linux CI", "Avoid relying on local-only executable permissions", "Verify postinstall scripts in clean environments"],
  },
  {
    id: "VERCEL_ENV_VAR_MISSING",
    label: "Vercel environment variable missing",
    description: "A variable needed by Vercel build or runtime is missing from the active deployment scope.",
    symptoms: ["Environment Variable is not set", "vercel env", "Missing required environment variable"],
    likelyCauses: ["Variable missing in Preview or Production", "Secret only exists locally", "Env name differs from code"],
    fixSteps: ["Add the variable in Vercel Project Settings", "Verify preview and production scopes", "Keep .env.example synchronized"],
    verificationCommands: ["npm run build", "vercel env ls"],
    preventionChecks: ["Track required env vars in docs", "Fail with safe validation messages", "Never commit secret values"],
  },
  {
    id: "ESLINT_BUILD_ERROR",
    label: "ESLint build failure",
    description: "The production build failed because lint checks reported blocking errors.",
    symptoms: ["Failed to compile", "ESLint", "Linting and checking validity of types"],
    likelyCauses: ["Blocking lint violation", "Unused imports or invalid hook usage", "Rule mismatch between local and CI"],
    fixSteps: ["Fix the reported lint violation", "Remove unused code instead of suppressing rules", "Run lint before build when available"],
    verificationCommands: ["npm run lint", "npm run build"],
    preventionChecks: ["Keep lint in CI", "Avoid blanket disables", "Use focused component tests for hook-heavy code"],
  },
  {
    id: "VITE_BUILD_ERROR",
    label: "Vite build failure",
    description: "A Vite app failed during production build or Rollup bundling.",
    symptoms: ["vite build", "Rollup failed to resolve import", "Transform failed"],
    likelyCauses: ["Bad import path", "Missing dependency", "Vite env or asset configuration mismatch"],
    fixSteps: ["Repair the import or dependency", "Check Vite env prefixes", "Run the app's production build locally"],
    verificationCommands: ["npm run build"],
    preventionChecks: ["Run Vite builds in CI", "Keep env prefixes documented", "Avoid framework-specific assumptions across apps"],
  },
  {
    id: "PRISMA_DATABASE_ERROR",
    label: "Prisma database configuration error",
    description: "Prisma failed because database configuration or generation is missing.",
    symptoms: ["PrismaClientInitializationError", "DATABASE_URL", "prisma generate"],
    likelyCauses: ["Invalid DATABASE_URL", "Prisma client not generated", "Database unavailable during build"],
    fixSteps: ["Validate DATABASE_URL in Vercel env", "Run prisma generate during build if needed", "Avoid live DB queries at build time"],
    verificationCommands: ["npx prisma validate", "npx prisma generate", "npm run build"],
    preventionChecks: ["Use pooled production URLs", "Keep migrations separate from builds", "Redact database URLs in logs"],
  },
  {
    id: "SUPABASE_CONFIG_ERROR",
    label: "Supabase configuration error",
    description: "Supabase client setup is missing required project URL or anon/service key values.",
    symptoms: ["supabaseUrl is required", "NEXT_PUBLIC_SUPABASE_URL", "SUPABASE_ANON_KEY"],
    likelyCauses: ["Missing public Supabase URL", "Wrong env scope", "Using service key in client code"],
    fixSteps: ["Add public URL and anon key to the correct Vercel scope", "Keep service-role keys server-only", "Rebuild after updating env"],
    verificationCommands: ["npm run build", "vercel env ls"],
    preventionChecks: ["Separate public and server env names", "Never expose service-role keys", "Add env schema tests"],
  },
  {
    id: "STRIPE_WEBHOOK_ERROR",
    label: "Stripe webhook configuration error",
    description: "Stripe webhook verification cannot run because the signing secret or route config is wrong.",
    symptoms: ["STRIPE_WEBHOOK_SECRET", "No signatures found", "webhook secret missing"],
    likelyCauses: ["Webhook secret missing in Vercel", "Raw body not preserved", "Wrong endpoint secret for environment"],
    fixSteps: ["Add STRIPE_WEBHOOK_SECRET to Vercel", "Verify the route uses raw body where required", "Use test/live secrets in matching environments"],
    verificationCommands: ["npm run build", "stripe listen --forward-to localhost:3000/api/webhooks/stripe"],
    preventionChecks: ["Document test vs live webhook secrets", "Never log webhook secrets", "Add route-level webhook tests"],
  },
  {
    id: "VERCEL_RUNTIME_ERROR",
    label: "Vercel runtime mismatch",
    description: "A route or function uses APIs incompatible with the selected Vercel runtime.",
    symptoms: ["Edge Runtime", "Node.js APIs are not available", "Function Runtimes must have a valid version"],
    likelyCauses: ["Node-only package imported in Edge runtime", "Unsupported runtime setting", "Function exceeds runtime limits"],
    fixSteps: ["Switch route runtime to nodejs or remove Node-only APIs", "Check vercel.json function settings", "Redeploy after runtime alignment"],
    verificationCommands: ["npm run build", "vercel --prod"],
    preventionChecks: ["Declare route runtime intentionally", "Keep runtime-specific packages isolated", "Review Vercel function limits"],
  },
  {
    id: "OUT_OF_MEMORY",
    label: "Build timeout or memory pressure",
    description: "The build or serverless function exceeded memory or duration limits.",
    symptoms: ["JavaScript heap out of memory", "timed out", "exceeded memory limit"],
    likelyCauses: ["Large static generation workload", "Unbounded build-time data fetch", "Bundle or image processing spike"],
    fixSteps: ["Reduce build-time work", "Paginate or cache data generation", "Inspect bundle and function size"],
    verificationCommands: ["npm run build", "NODE_OPTIONS=--max_old_space_size=4096 npm run build"],
    preventionChecks: ["Track build duration", "Avoid unbounded static generation", "Monitor function memory"],
  },
  {
    id: "SERVERLESS_FUNCTION_LIMIT",
    label: "Serverless function size or duration limit",
    description: "A Vercel serverless function exceeded bundle, memory, or execution constraints.",
    symptoms: ["Serverless Function has exceeded", "FUNCTION_INVOCATION_TIMEOUT", "function size limit"],
    likelyCauses: ["Large dependency included in a route", "Unbounded request-time work", "Wrong runtime for workload"],
    fixSteps: ["Move heavy dependencies out of hot routes", "Stream or paginate long work", "Review Vercel function settings and limits"],
    verificationCommands: ["npm run build", "vercel --prod"],
    preventionChecks: ["Inspect function traces", "Keep route dependencies small", "Use background jobs for long work"],
  },
  {
    id: "UNKNOWN",
    label: "Unknown failure",
    description: "The log does not match a known deterministic failure pattern.",
    symptoms: ["Unclassified error lines"],
    likelyCauses: ["Insufficient log detail", "New framework or provider error", "Multiple overlapping failures"],
    fixSteps: ["Collect full build logs", "Search for the first fatal error", "Re-run with verbose logging"],
    verificationCommands: ["npm run build"],
    preventionChecks: ["Keep structured logs", "Capture build command and environment", "Add new recipe after triage"],
  },
] satisfies Array<ReturnType<typeof taxonomyEntrySchema.parse>>;

export const taxonomyById = Object.fromEntries(
  failureTaxonomy.map((entry) => [entry.id, entry]),
) as Record<FailureType, (typeof failureTaxonomy)[number]>;
