import type { FailureType, PatchDraft } from "./schemas";

type PatchRecipe = {
  fallbackFiles: string[];
  title: string;
  rationale: string;
  snippetLanguage: NonNullable<PatchDraft["snippetLanguage"]>;
  snippet: string;
  verificationCommands: string[];
  risks: string[];
  confidence: PatchDraft["confidence"];
};

const patchRecipes: Record<FailureType, PatchRecipe> = {
  MISSING_ENV_VAR: {
    fallbackFiles: [".env.example", "vercel.json"],
    title: "Add the missing environment variable to the expected scope",
    rationale: "The build is failing before runtime because a required configuration value is unavailable in the active Vercel environment.",
    snippetLanguage: "env",
    snippet: "NEXT_PUBLIC_REQUIRED_KEY=\n# Add the same key in Vercel Project Settings for Preview and Production as needed.",
    verificationCommands: ["npm run build", "vercel env ls"],
    risks: ["The variable may exist in preview but not production.", "A public value may be incorrectly treated as server-only or the reverse."],
    confidence: "high",
  },
  TYPESCRIPT_ERROR: {
    fallbackFiles: ["src/components/DeploymentCard.tsx"],
    title: "Align the referenced type contract with the component usage",
    rationale: "The build failed during type checking, so the safest fix is to bring the component props or data model back into agreement.",
    snippetLanguage: "ts",
    snippet: "type BuildRecord = {\n  deploymentUrl?: string;\n  // add or correct only the fields the component actually reads\n};",
    verificationCommands: ["npm run typecheck", "npm run build"],
    risks: ["The failing property may be produced by an API response that also needs schema validation."],
    confidence: "high",
  },
  MODULE_NOT_FOUND: {
    fallbackFiles: ["src/app/page.tsx", "tsconfig.json"],
    title: "Repair the unresolved import or missing dependency",
    rationale: "The bundler cannot resolve a path or package, so the patch should correct the import target or restore the missing module.",
    snippetLanguage: "ts",
    snippet: "import { BuildPanel } from \"@/components/BuildPanel\";\n// If the file moved, update the import path casing and alias target to the real file.",
    verificationCommands: ["npm install", "npm run build"],
    risks: ["Case-sensitive path issues may only appear in Linux build environments.", "Installing a package may not be correct if the import path is wrong."],
    confidence: "high",
  },
  NEXT_BUILD_ERROR: {
    fallbackFiles: ["src/app/dashboard/page.tsx", "src/app/api"],
    title: "Move dynamic behavior behind an explicit server boundary",
    rationale: "Next.js is rejecting the route because static rendering and dynamic APIs are being mixed in an unsupported way.",
    snippetLanguage: "ts",
    snippet: "export const dynamic = \"force-dynamic\";\n\n// or move cookies()/headers() usage into a route handler or server action.",
    verificationCommands: ["npm run build"],
    risks: ["Forcing dynamic rendering can change caching behavior.", "Server/client boundary issues may require moving imports rather than route flags."],
    confidence: "medium",
  },
  NEXT_STATIC_GENERATION_ERROR: {
    fallbackFiles: ["src/app/page.tsx", "src/app/[route]/page.tsx"],
    title: "Make static generation deterministic or opt the route into dynamic rendering",
    rationale: "The route failed during prerendering, so dynamic data access must be guarded or moved behind an explicit runtime boundary.",
    snippetLanguage: "ts",
    snippet: "export const dynamic = \"force-dynamic\";\n\n// Prefer this only when the page cannot be safely prerendered.",
    verificationCommands: ["npm run build"],
    risks: ["Dynamic rendering can change caching and SEO behavior.", "The real root cause may be an unhandled build-time fetch error."],
    confidence: "medium",
  },
  APP_ROUTER_ROUTE_HANDLER_ERROR: {
    fallbackFiles: ["src/app/api/example/route.ts"],
    title: "Harden the App Router route handler boundary",
    rationale: "The route handler needs safe request parsing, explicit runtime assumptions, and user-safe error responses.",
    snippetLanguage: "ts",
    snippet: "export async function POST(request: Request) {\n  const body = await request.json().catch(() => null);\n  if (!body) return Response.json({ error: \"Invalid request\" }, { status: 400 });\n  return Response.json({ ok: true });\n}",
    verificationCommands: ["npm run typecheck", "npm run build"],
    risks: ["Route behavior may depend on server-only env vars.", "Provider code must stay out of client bundles."],
    confidence: "medium",
  },
  PACKAGE_INSTALL_ERROR: {
    fallbackFiles: ["package.json", "package-lock.json"],
    title: "Resolve the dependency conflict at the package manifest level",
    rationale: "The failure occurs before app build, so the patch should reconcile version ranges or refresh the lockfile with the intended dependency tree.",
    snippetLanguage: "json",
    snippet: "{\n  \"dependencies\": {\n    \"react\": \"^19.0.0\"\n  }\n}\n// Then regenerate the lockfile with npm install.",
    verificationCommands: ["npm install", "npm run build"],
    risks: ["Changing peer dependency ranges can affect runtime behavior.", "Lockfile regeneration should use the repo's package manager only."],
    confidence: "medium",
  },
  PNPM_LOCKFILE_MISMATCH: {
    fallbackFiles: ["package.json", "pnpm-lock.yaml"],
    title: "Regenerate the pnpm lockfile with the intended package graph",
    rationale: "The install is blocked before build because package.json and pnpm-lock.yaml disagree under frozen-lockfile rules.",
    snippetLanguage: "bash",
    snippet: "pnpm install\npnpm install --frozen-lockfile\npnpm build",
    verificationCommands: ["pnpm install --frozen-lockfile", "pnpm build"],
    risks: ["This repo may use npm instead of pnpm; do not introduce a second package manager.", "Lockfile changes need dependency review."],
    confidence: "medium",
  },
  PACKAGE_JSON_PARSE: {
    fallbackFiles: ["package.json"],
    title: "Repair invalid package manifest JSON",
    rationale: "The package manager cannot parse the manifest, so dependency installation and build startup are blocked before application code runs.",
    snippetLanguage: "json",
    snippet: "{\n  \"scripts\": {\n    \"build\": \"next build\"\n  }\n}\n// Remove trailing commas, comments, and merge-conflict markers before running npm install.",
    verificationCommands: ["node -e \"JSON.parse(require('fs').readFileSync('package.json','utf8'))\"", "npm install", "npm run build"],
    risks: ["A merge conflict marker may hide a larger dependency change.", "Do not hand-edit package-lock.json until package.json parses."],
    confidence: "high",
  },
  SPAWN_PERMISSION: {
    fallbackFiles: ["package.json", "scripts/**"],
    title: "Make the failing build script portable and executable",
    rationale: "The build cannot start a required process, usually because a script, binary, or shell assumption is not valid in the deployment environment.",
    snippetLanguage: "json",
    snippet: "{\n  \"scripts\": {\n    \"build\": \"next build\"\n  }\n}\n// Replace local-only shell commands with portable npm scripts where possible.",
    verificationCommands: ["npm install", "npm run build"],
    risks: ["Executable permissions may differ between local Windows/macOS and Linux CI.", "A missing binary can indicate a skipped install step."],
    confidence: "medium",
  },
  VERCEL_ENV_VAR_MISSING: {
    fallbackFiles: [".env.example", "vercel.json"],
    title: "Add the missing variable to the active Vercel environment scope",
    rationale: "The app expects a variable that is absent from Vercel preview or production settings.",
    snippetLanguage: "env",
    snippet: "REQUIRED_ENV_NAME=\n# Store the real value in Vercel Project Settings, not in source control.",
    verificationCommands: ["npm run build", "vercel env ls"],
    risks: ["Preview and production scopes may differ.", "Secret values must remain server-side unless explicitly public."],
    confidence: "high",
  },
  ESLINT_BUILD_ERROR: {
    fallbackFiles: ["src/**"],
    title: "Fix the lint violation blocking production build",
    rationale: "The build gate is failing on lint, so the correct patch is to address the reported rule rather than disable the build check.",
    snippetLanguage: "ts",
    snippet: "// Remove unused imports, fix hook dependencies, or correct the reported lint issue at the source.",
    verificationCommands: ["npm run lint", "npm run build"],
    risks: ["This repo may not define a lint script.", "Suppressing rules can hide actual runtime bugs."],
    confidence: "medium",
  },
  VITE_BUILD_ERROR: {
    fallbackFiles: ["src/main.tsx", "vite.config.ts"],
    title: "Repair the Vite/Rollup build input or import graph",
    rationale: "The Vite build failed during transform or bundling, usually from an unresolved import, asset, or env prefix issue.",
    snippetLanguage: "ts",
    snippet: "// Check vite.config.ts aliases and update imports to match the real file path and casing.",
    verificationCommands: ["npm run build"],
    risks: ["Vite env variables require the expected public prefix.", "Case mismatches can pass locally and fail in Linux CI."],
    confidence: "medium",
  },
  PRISMA_DATABASE_ERROR: {
    fallbackFiles: ["prisma/schema.prisma", ".env.example"],
    title: "Restore Prisma configuration before build-time access",
    rationale: "Prisma cannot initialize unless the database URL and generated client are valid for the build environment.",
    snippetLanguage: "env",
    snippet: "DATABASE_URL=\"[REDACTED_DATABASE_URL]\"\n# Add the real value only in Vercel environment settings, never in source.",
    verificationCommands: ["npx prisma validate", "npx prisma generate", "npm run build"],
    risks: ["Database access during static build can still fail after env repair.", "Connection strings must remain server-only."],
    confidence: "high",
  },
  SUPABASE_CONFIG_ERROR: {
    fallbackFiles: ["src/lib/supabase.ts", ".env.example"],
    title: "Provide the public Supabase configuration expected by the client",
    rationale: "The client bootstrap is failing because the public project URL or anon key was unavailable in the captured build environment.",
    snippetLanguage: "env",
    snippet: "NEXT_PUBLIC_SUPABASE_URL=\"https://project.supabase.co\"\nNEXT_PUBLIC_SUPABASE_ANON_KEY=\"public-anon-key\"\n# Keep service-role keys out of client code.",
    verificationCommands: ["npm run build", "vercel env ls"],
    risks: ["Service-role keys must not be exposed to client bundles.", "Preview and production env scopes can diverge."],
    confidence: "high",
  },
  STRIPE_WEBHOOK_ERROR: {
    fallbackFiles: ["src/app/api/webhooks/stripe/route.ts", ".env.example"],
    title: "Add the webhook signing secret and preserve the raw request body",
    rationale: "Stripe webhook verification will fail until the route has the matching secret and request handling strategy.",
    snippetLanguage: "env",
    snippet: "STRIPE_WEBHOOK_SECRET=\"[REDACTED_SECRET]\"\n# Ensure the webhook route verifies the raw payload with the matching environment secret.",
    verificationCommands: ["npm run build", "stripe listen --forward-to localhost:3000/api/webhooks/stripe"],
    risks: ["Test and live webhook secrets are not interchangeable.", "Raw request body handling must match the Stripe SDK verification path."],
    confidence: "high",
  },
  VERCEL_RUNTIME_ERROR: {
    fallbackFiles: ["src/app/api/chat/route.ts", "vercel.json"],
    title: "Match the function runtime to the APIs imported by the route",
    rationale: "The route is using APIs that do not fit the configured runtime, so the patch should either switch runtimes or remove incompatible imports.",
    snippetLanguage: "ts",
    snippet: "export const runtime = \"nodejs\";\n// Use this when the route depends on Node-only APIs that Edge cannot provide.",
    verificationCommands: ["npm run build", "vercel --prod"],
    risks: ["Changing runtime can affect latency and available APIs.", "The better fix may be removing Node-only imports from Edge routes."],
    confidence: "medium",
  },
  OUT_OF_MEMORY: {
    fallbackFiles: ["src/app/page.tsx", "next.config.ts"],
    title: "Reduce build-time work before increasing resource usage",
    rationale: "The build is exceeding memory or time limits, so the first patch should trim expensive static work or bundle pressure.",
    snippetLanguage: "bash",
    snippet: "NODE_OPTIONS=--max_old_space_size=4096 npm run build\n# Then move large build-time fetches or generation behind caching or pagination.",
    verificationCommands: ["npm run build", "NODE_OPTIONS=--max_old_space_size=4096 npm run build"],
    risks: ["Increasing memory can mask unbounded build-time work.", "Function limits may still fail after local build success."],
    confidence: "medium",
  },
  SERVERLESS_FUNCTION_LIMIT: {
    fallbackFiles: ["src/app/api/**/route.ts", "vercel.json"],
    title: "Reduce serverless route bundle size or execution time",
    rationale: "The function exceeded Vercel runtime constraints, so heavy imports or long-running work need to move out of the request path.",
    snippetLanguage: "ts",
    snippet: "// Move heavy dependencies behind server-only boundaries and avoid unbounded request-time work in route handlers.",
    verificationCommands: ["npm run build", "vercel --prod"],
    risks: ["Increasing limits can hide architectural problems.", "Function traces may be needed to identify the heaviest dependency."],
    confidence: "medium",
  },
  UNKNOWN: {
    fallbackFiles: [],
    title: "Collect more context before drafting a code change",
    rationale: "The current log does not provide enough deterministic signal to produce a trustworthy patch snippet.",
    snippetLanguage: "text",
    snippet: "# No automatic patch suggested.\n# Re-run the build with verbose logging and inspect the first failing stack frame.",
    verificationCommands: ["npm run build", "npm test"],
    risks: ["The root cause may require repository-specific context.", "Applying a generic patch could hide the real failure."],
    confidence: "low",
  },
};

export function buildPatchDraft(type: FailureType, affectedFiles: string[]): PatchDraft {
  const recipe = patchRecipes[type] ?? patchRecipes.UNKNOWN;
  const likelyAffectedFiles = affectedFiles.length ? affectedFiles : recipe.fallbackFiles;
  return {
    title: recipe.title,
    failureType: type,
    likelyAffectedFiles,
    rationale: recipe.rationale,
    snippet: recipe.snippet,
    verificationCommands: recipe.verificationCommands,
    risks: recipe.risks,
    confidence: recipe.confidence,
    affectedFiles: likelyAffectedFiles,
    snippetLanguage: recipe.snippetLanguage,
    verificationNote: recipe.verificationCommands.length ? `Run ${recipe.verificationCommands.join(", ")} after applying the change.` : "Run the project verification commands after applying the change.",
  };
}
