import type { Diagnosis } from "@/lib/schemas";
import { InfoTip } from "./InfoTip";

export function TraceTimeline({ diagnosis }: { diagnosis: Diagnosis }) {
  return (
    <section className="rounded-2xl border border-white/10 bg-white/[0.035] p-5">
      <h3 className="text-lg font-semibold text-white">
        Local diagnostic trace{" "}
        <InfoTip label="Trace">A deterministic receipt showing how the local diagnosis engine evaluated the pasted log.</InfoTip>
      </h3>
      <p className="mt-2 text-sm leading-6 text-slate-300">
        This trace is generated by the local Build Doctor pipeline. It is not a model chain-of-thought or provider trace.
      </p>
      <div className="mt-3 rounded-2xl border border-cyan/20 bg-cyan/10 p-3 text-xs uppercase tracking-[0.14em] text-cyan">
        Local deterministic run: {diagnosis.graphRun.nodeSequence.length} steps / checkpoint-safe snapshot
      </div>
      <div className="mt-4 space-y-3">
        {diagnosis.traceSteps.map((step, index) => (
          <article key={step.id} className="rounded-2xl border border-white/10 bg-black/25 p-3.5">
            <div className="flex flex-wrap items-start justify-between gap-3">
              <div className="flex items-center gap-3">
                <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-cyan/35 bg-cyan/10 font-mono text-[11px] text-cyan">
                  {index + 1}
                </span>
                <div>
                  <p className="text-xs font-semibold uppercase tracking-[0.16em] text-cyan">{step.label}</p>
                  <h4 className="mt-1 text-base font-semibold text-white">{step.outputSummary}</h4>
                </div>
              </div>
              <span
                className={`rounded-full px-2.5 py-1 text-[10px] font-semibold uppercase tracking-[0.14em] ${
                  step.status === "complete"
                    ? "border border-white/15 bg-white/[0.04] text-slate-300"
                    : "border border-dashed border-gold/70 bg-gold/10 text-gold"
                }`}
              >
                {step.status.toUpperCase()}
              </span>
            </div>
            <p className="mt-3 text-sm leading-6 text-slate-300">{step.inputSummary}</p>
            <div className="mt-3 flex flex-wrap gap-2 text-[10px] font-semibold uppercase tracking-[0.12em] text-slate-400">
              <span>Evidence refs:</span>
              {step.evidenceRefs.length ? (
                step.evidenceRefs.map((ref) => (
                  <span key={ref} className="rounded-full border border-white/10 bg-white/[0.035] px-2 py-0.5">
                    {ref}
                  </span>
                ))
              ) : (
                <span className="rounded-full border border-white/10 bg-white/[0.035] px-2 py-0.5">none</span>
              )}
            </div>
          </article>
        ))}
      </div>
    </section>
  );
}
